In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot
%matplotlib inline
from scipy.stats import pearsonr

In [40]:
main=pd.read_csv("Second Trimester.csv")
main.set_index(["Unnamed: 0"], inplace=True)

In [41]:
main

                BPD      HC      AC       FL      TCD     LMP
Unnamed: 0
1            20w 2d  21w 1d  22w 0d   20w 5d   20w 4d   20w 4
2            25w 3d  24w 1d  27w 2d   26w 1d   26w 2d  26w 2d
3            19w 1d  20w 2d  21w 1d   20w 5d   20w 4d  20w 4d
4            24w 2d  26w 1d  27w 1d   25w 6d   26w 1d  26w 0d
5            18w 2d  19w 1d  19w 6d   20w 1d   19w 1d  19w 3d
6            21w 1d  22w 1d  22w 0d   21w 5d   21w 5d  22w 0d
7            27w 1d  28w 2d  28w 3d   26w 4d   27w 1d  27w 0d
8            23w 4d  22w 1d  23w 6d   23w 0d   22w 5d  23w 0d
9            24w 3d  25w 1d  25w 6d   24w 6d   24w 0d  24w 0d
10           22w 4d  22w 6d  21w 5d   20w 5d   21w 6d  21w 6d
11           19w 2d  18w 3d  21w 0d   20w 4d   19w 3d  19w 3d
12           27w 1d  26w 4d  28w 0d   28w 1d   26w 1d  26w 0d
13           23w 1d  22w 5d  22w 5d   23w 4d   23w 0d  23w 0d
14           20w 4d  20w 5d  20w 3d   21w 2d   21w 2d  20w 0d
15           25w 2d  25w 5d  25w 1d   25w 4d   25w 0d  25w 0d
16           23w 2d  23w 0d  23w 1d   24w 2d   24w 2d  24w 2d
17           25w 4d  24w 1d  23w 5d   26w 3d   26w 4d  26w 0d
18           22w 4d  22w 0d  21w 3d   22w 0d   22w 0d  22w 0d
19           21w 5d  22w 0d  22w 2d   22w 0d   22w 1d  22w 0d
20           24w 2d  25w 0d  20w 5d   21w 0d   24w 6d  20w 5d
21           20w 0d  19w 5d  22w 5d   23w 1d   22w 0d  20w 0d
22           21w 0d  21w 3d  21w 1d   21w 4d   21w 5d  21w 1d
23           20w 6d  21w 0d  24w 5d   23w 0d   23w 0d  24w 0d
24           23w 5d  23w 2d  20w 1d   21w 2d   20w 4d  23w 0d
25           20w 3d  19w 5d  23w 2d   23w 5d   23w 4d  24w 0d
26           21w 1d  22w 0d  22w 6d   23w 0d   22w 5d  23w 0d
27           26w 6d  28w 0d  25w 2d   26w 4d  26w 5d   26w 5d
28           18w 2d  18w 2d  18w 6d   19w 1d   19w 0d  19w 0d
29           23w 2d  22w 3d  23w 1d   22w 5d   23w 0d  23w 0d
30           20w 0d  20w 3d  19w 5d   20w 0d   19w 6d  20w 0d
31           22w 4d  22w 3d  22w 2d   22w 5d   22w 4d  22w 5d
32           20w 6d  21w 3d  23w 0d   21w 5d   21w 5d  22w 0d
33           22w 0d  22w 3d  22w 0d   21w 6d   22w 0d  22w 0d
34           19w 5d  18w 6d  19w 0d   19w 0d   19w 1d  19w 0d
35           26w 4d  26w 6d  27w 2d   27w 6d   27w 5d  28w 0d
36          23w 4d   24w 0d  23w 6d  24w 0d    24w 0d  24w 0d
37           24w 2d  24w 3d  26w 0d   25w 3d   25w 2d  26w 0d
38           19w 4d  20w 0d  19w 6d   19w 6d   19w 5d  20w 0d
39           22w 5d  22w 5d  23w 0d   22w 3d   22w 3d  22w 3d
40           26w 0d  26w 3d  25w 3d   25w 5d   25w 4d  26w 0d
41           25w 4d  25w 3d  27w 6d   27w 0d   27w 2d  27w 0d
42           23w 3d  23w 3d  24w 0d   23w 5d   23w 5d  23w 0d
43           20w 2d  20w 6d  22w 0d   21w 5d   21w 3d  21w 0d
44           19w 6d  20w 0d  19w 5d   19w 6d   20w 0d  20w 0d
45          25w 45d  25w 5d  26w 5d   26w 0d   26w 2d  26w 0d

In [42]:

s=main["BPD"].str.replace("w","", regex=False)
l=s.str.rsplit("d",expand=True,n=1)
pd.DataFrame( l)

main.columns

Index(['BPD', 'HC', 'AC', 'FL', 'TCD', 'LMP'], dtype='object')

In [43]:
m=['BPD', 'HC', 'AC', 'FL', 'TCD', 'LMP']
main=main[m].replace({"w":".","d":""},regex=True)
main

               BPD     HC     AC      FL     TCD    LMP
Unnamed: 0
1            20. 2  21. 1  22. 0   20. 5   20. 4  20. 4
2            25. 3  24. 1  27. 2   26. 1   26. 2  26. 2
3            19. 1  20. 2  21. 1   20. 5   20. 4  20. 4
4            24. 2  26. 1  27. 1   25. 6   26. 1  26. 0
5            18. 2  19. 1  19. 6   20. 1   19. 1  19. 3
6            21. 1  22. 1  22. 0   21. 5   21. 5  22. 0
7            27. 1  28. 2  28. 3   26. 4   27. 1  27. 0
8            23. 4  22. 1  23. 6   23. 0   22. 5  23. 0
9            24. 3  25. 1  25. 6   24. 6   24. 0  24. 0
10           22. 4  22. 6  21. 5   20. 5   21. 6  21. 6
11           19. 2  18. 3  21. 0   20. 4   19. 3  19. 3
12           27. 1  26. 4  28. 0   28. 1   26. 1  26. 0
13           23. 1  22. 5  22. 5   23. 4   23. 0  23. 0
14           20. 4  20. 5  20. 3   21. 2   21. 2  20. 0
15           25. 2  25. 5  25. 1   25. 4   25. 0  25. 0
16           23. 2  23. 0  23. 1   24. 2   24. 2  24. 2
17           25. 4  24. 1  23. 5   26. 3   26. 4  26. 0
18           22. 4  22. 0  21. 3   22. 0   22. 0  22. 0
19           21. 5  22. 0  22. 2   22. 0   22. 1  22. 0
20           24. 2  25. 0  20. 5   21. 0   24. 6  20. 5
21           20. 0  19. 5  22. 5   23. 1   22. 0  20. 0
22           21. 0  21. 3  21. 1   21. 4   21. 5  21. 1
23           20. 6  21. 0  24. 5   23. 0   23. 0  24. 0
24           23. 5  23. 2  20. 1   21. 2   20. 4  23. 0
25           20. 3  19. 5  23. 2   23. 5   23. 4  24. 0
26           21. 1  22. 0  22. 6   23. 0   22. 5  23. 0
27           26. 6  28. 0  25. 2   26. 4  26. 5   26. 5
28           18. 2  18. 2  18. 6   19. 1   19. 0  19. 0
29           23. 2  22. 3  23. 1   22. 5   23. 0  23. 0
30           20. 0  20. 3  19. 5   20. 0   19. 6  20. 0
31           22. 4  22. 3  22. 2   22. 5   22. 4  22. 5
32           20. 6  21. 3  23. 0   21. 5   21. 5  22. 0
33           22. 0  22. 3  22. 0   21. 6   22. 0  22. 0
34           19. 5  18. 6  19. 0   19. 0   19. 1  19. 0
35           26. 4  26. 6  27. 2   27. 6   27. 5  28. 0
36          23. 4   24. 0  23. 6  24. 0    24. 0  24. 0
37           24. 2  24. 3  26. 0   25. 3   25. 2  26. 0
38           19. 4  20. 0  19. 6   19. 6   19. 5  20. 0
39           22. 5  22. 5  23. 0   22. 3   22. 3  22. 3
40           26. 0  26. 3  25. 3   25. 5   25. 4  26. 0
41           25. 4  25. 3  27. 6   27. 0   27. 2  27. 0
42           23. 3  23. 3  24. 0   23. 5   23. 5  23. 0
43           20. 2  20. 6  22. 0   21. 5   21. 3  21. 0
44           19. 6  20. 0  19. 5   19. 6   20. 0  20. 0
45          25. 45  25. 5  26. 5   26. 0   26. 2  26. 0

In [44]:
main_1=main[m].replace({". ":" "},regex=True)
main_1

              BPD    HC    AC    FL   TCD   LMP
Unnamed: 0
1            20 2  21 1  22 0  20 5  20 4  20 4
2            25 3  24 1  27 2  26 1  26 2  26 2
3            19 1  20 2  21 1  20 5  20 4  20 4
4            24 2  26 1  27 1  25 6  26 1  26 0
5            18 2  19 1  19 6  20 1  19 1  19 3
6            21 1  22 1  22 0  21 5  21 5  22 0
7            27 1  28 2  28 3  26 4  27 1  27 0
8            23 4  22 1  23 6  23 0  22 5  23 0
9            24 3  25 1  25 6  24 6  24 0  24 0
10           22 4  22 6  21 5  20 5  21 6  21 6
11           19 2  18 3  21 0  20 4  19 3  19 3
12           27 1  26 4  28 0  28 1  26 1  26 0
13           23 1  22 5  22 5  23 4  23 0  23 0
14           20 4  20 5  20 3  21 2  21 2  20 0
15           25 2  25 5  25 1  25 4  25 0  25 0
16           23 2  23 0  23 1  24 2  24 2  24 2
17           25 4  24 1  23 5  26 3  26 4  26 0
18           22 4  22 0  21 3  22 0  22 0  22 0
19           21 5  22 0  22 2  22 0  22 1  22 0
20           24 2  25 0  20 5  21 0  24 6  20 5
21           20 0  19 5  22 5  23 1  22 0  20 0
22           21 0  21 3  21 1  21 4  21 5  21 1
23           20 6  21 0  24 5  23 0  23 0  24 0
24           23 5  23 2  20 1  21 2  20 4  23 0
25           20 3  19 5  23 2  23 5  23 4  24 0
26           21 1  22 0  22 6  23 0  22 5  23 0
27           26 6  28 0  25 2  26 4  26    26 5
28           18 2  18 2  18 6  19 1  19 0  19 0
29           23 2  22 3  23 1  22 5  23 0  23 0
30           20 0  20 3  19 5  20 0  19 6  20 0
31           22 4  22 3  22 2  22 5  22 4  22 5
32           20 6  21 3  23 0  21 5  21 5  22 0
33           22 0  22 3  22 0  21 6  22 0  22 0
34           19 5  18 6  19 0  19 0  19 1  19 0
35           26 4  26 6  27 2  27 6  27 5  28 0
36           23    24 0  23 6  24    24 0  24 0
37           24 2  24 3  26 0  25 3  25 2  26 0
38           19 4  20 0  19 6  19 6  19 5  20 0
39           22 5  22 5  23 0  22 3  22 3  22 3
40           26 0  26 3  25 3  25 5  25 4  26 0
41           25 4  25 3  27 6  27 0  27 2  27 0
42           23 3  23 3  24 0  23 5  23 5  23 0
43           20 2  20 6  22 0  21 5  21 3  21 0
44           19 6  20 0  19 5  19 6  20 0  20 0
45          25 45  25 5  26 5  26 0  26 2  26 0

In [45]:
main_2=main_1['BPD'].str.split(" ", n=1, expand=True)
main_1["BPD/Weeks"]=main_2[0]
main_1["BPD/Days"]=main_2[1]
main_1

              BPD    HC    AC    FL   TCD   LMP BPD/Weeks BPD/Days
Unnamed: 0
1            20 2  21 1  22 0  20 5  20 4  20 4        20        2
2            25 3  24 1  27 2  26 1  26 2  26 2        25        3
3            19 1  20 2  21 1  20 5  20 4  20 4        19        1
4            24 2  26 1  27 1  25 6  26 1  26 0        24        2
5            18 2  19 1  19 6  20 1  19 1  19 3        18        2
6            21 1  22 1  22 0  21 5  21 5  22 0        21        1
7            27 1  28 2  28 3  26 4  27 1  27 0        27        1
8            23 4  22 1  23 6  23 0  22 5  23 0        23        4
9            24 3  25 1  25 6  24 6  24 0  24 0        24        3
10           22 4  22 6  21 5  20 5  21 6  21 6        22        4
11           19 2  18 3  21 0  20 4  19 3  19 3        19        2
12           27 1  26 4  28 0  28 1  26 1  26 0        27        1
13           23 1  22 5  22 5  23 4  23 0  23 0        23        1
14           20 4  20 5  20 3  21 2  21 2  20 0        20        4
15           25 2  25 5  25 1  25 4  25 0  25 0        25        2
16           23 2  23 0  23 1  24 2  24 2  24 2        23        2
17           25 4  24 1  23 5  26 3  26 4  26 0        25        4
18           22 4  22 0  21 3  22 0  22 0  22 0        22        4
19           21 5  22 0  22 2  22 0  22 1  22 0        21        5
20           24 2  25 0  20 5  21 0  24 6  20 5        24        2
21           20 0  19 5  22 5  23 1  22 0  20 0        20        0
22           21 0  21 3  21 1  21 4  21 5  21 1        21        0
23           20 6  21 0  24 5  23 0  23 0  24 0        20        6
24           23 5  23 2  20 1  21 2  20 4  23 0        23        5
25           20 3  19 5  23 2  23 5  23 4  24 0        20        3
26           21 1  22 0  22 6  23 0  22 5  23 0        21        1
27           26 6  28 0  25 2  26 4  26    26 5        26        6
28           18 2  18 2  18 6  19 1  19 0  19 0        18        2
29           23 2  22 3  23 1  22 5  23 0  23 0        23        2
30           20 0  20 3  19 5  20 0  19 6  20 0        20        0
31           22 4  22 3  22 2  22 5  22 4  22 5        22        4
32           20 6  21 3  23 0  21 5  21 5  22 0        20        6
33           22 0  22 3  22 0  21 6  22 0  22 0        22        0
34           19 5  18 6  19 0  19 0  19 1  19 0        19        5
35           26 4  26 6  27 2  27 6  27 5  28 0        26        4
36           23    24 0  23 6  24    24 0  24 0        23
37           24 2  24 3  26 0  25 3  25 2  26 0        24        2
38           19 4  20 0  19 6  19 6  19 5  20 0        19        4
39           22 5  22 5  23 0  22 3  22 3  22 3        22        5
40           26 0  26 3  25 3  25 5  25 4  26 0        26        0
41           25 4  25 3  27 6  27 0  27 2  27 0        25        4
42           23 3  23 3  24 0  23 5  23 5  23 0        23        3
43           20 2  20 6  22 0  21 5  21 3  21 0        20        2
44           19 6  20 0  19 5  19 6  20 0  20 0        19        6
45          25 45  25 5  26 5  26 0  26 2  26 0        25       45

In [46]:
main_1["BPD/Days"].loc[36:37,]="1"
main_1

              BPD    HC    AC    FL   TCD   LMP BPD/Weeks BPD/Days
Unnamed: 0
1            20 2  21 1  22 0  20 5  20 4  20 4        20        2
2            25 3  24 1  27 2  26 1  26 2  26 2        25        3
3            19 1  20 2  21 1  20 5  20 4  20 4        19        1
4            24 2  26 1  27 1  25 6  26 1  26 0        24        2
5            18 2  19 1  19 6  20 1  19 1  19 3        18        2
6            21 1  22 1  22 0  21 5  21 5  22 0        21        1
7            27 1  28 2  28 3  26 4  27 1  27 0        27        1
8            23 4  22 1  23 6  23 0  22 5  23 0        23        4
9            24 3  25 1  25 6  24 6  24 0  24 0        24        3
10           22 4  22 6  21 5  20 5  21 6  21 6        22        4
11           19 2  18 3  21 0  20 4  19 3  19 3        19        2
12           27 1  26 4  28 0  28 1  26 1  26 0        27        1
13           23 1  22 5  22 5  23 4  23 0  23 0        23        1
14           20 4  20 5  20 3  21 2  21 2  20 0        20        4
15           25 2  25 5  25 1  25 4  25 0  25 0        25        2
16           23 2  23 0  23 1  24 2  24 2  24 2        23        2
17           25 4  24 1  23 5  26 3  26 4  26 0        25        4
18           22 4  22 0  21 3  22 0  22 0  22 0        22        4
19           21 5  22 0  22 2  22 0  22 1  22 0        21        5
20           24 2  25 0  20 5  21 0  24 6  20 5        24        2
21           20 0  19 5  22 5  23 1  22 0  20 0        20        0
22           21 0  21 3  21 1  21 4  21 5  21 1        21        0
23           20 6  21 0  24 5  23 0  23 0  24 0        20        6
24           23 5  23 2  20 1  21 2  20 4  23 0        23        5
25           20 3  19 5  23 2  23 5  23 4  24 0        20        3
26           21 1  22 0  22 6  23 0  22 5  23 0        21        1
27           26 6  28 0  25 2  26 4  26    26 5        26        6
28           18 2  18 2  18 6  19 1  19 0  19 0        18        2
29           23 2  22 3  23 1  22 5  23 0  23 0        23        2
30           20 0  20 3  19 5  20 0  19 6  20 0        20        0
31           22 4  22 3  22 2  22 5  22 4  22 5        22        4
32           20 6  21 3  23 0  21 5  21 5  22 0        20        6
33           22 0  22 3  22 0  21 6  22 0  22 0        22        0
34           19 5  18 6  19 0  19 0  19 1  19 0        19        5
35           26 4  26 6  27 2  27 6  27 5  28 0        26        4
36           23    24 0  23 6  24    24 0  24 0        23        1
37           24 2  24 3  26 0  25 3  25 2  26 0        24        1
38           19 4  20 0  19 6  19 6  19 5  20 0        19        4
39           22 5  22 5  23 0  22 3  22 3  22 3        22        5
40           26 0  26 3  25 3  25 5  25 4  26 0        26        0
41           25 4  25 3  27 6  27 0  27 2  27 0        25        4
42           23 3  23 3  24 0  23 5  23 5  23 0        23        3
43           20 2  20 6  22 0  21 5  21 3  21 0        20        2
44           19 6  20 0  19 5  19 6  20 0  20 0        19        6
45          25 45  25 5  26 5  26 0  26 2  26 0        25       45

In [47]:
main_1["BPD/Days"]=pd.to_numeric( main_1["BPD/Days"])
main_1["BPD/Days"].dtype

dtype('int64')

In [48]:
main_1["BPD/Weeks"]=pd.to_numeric(main_1["BPD/Weeks"])	
main_1.columns

Index(['BPD', 'HC', 'AC', 'FL', 'TCD', 'LMP', 'BPD/Weeks', 'BPD/Days'], dtype='object')

In [50]:
m3=main_1['HC'].str.split(" ", n=1, expand=True)
m4=main_1['AC'].str.split(" ", n=1, expand=True)
m5=main_1['FL'].str.split(" ", n=1, expand=True)
m6=main_1['TCD'].str.split(" ", n=1, expand=True)
m7=main_1['LMP'].str.split(" ", n=1, expand=True)
main_1['HC/Weeks']=m3[0]
main_1['AC/Weeks']=m4[0]
main_1['FL/Weeks']=m5[0]
main_1['TCD/Weeks']=m6[0]
main_1['LMP/Weeks']=m7[0]
main_1['HC/Days']=m3[1]
main_1['AC/Days']=m4[1]
main_1['FL/Days']=m5[1]
main_1['TCD/Days']=m6[1]
main_1['LMP/Days']=m7[1]

In [51]:
main_1

,BPD,HC,AC,FL,TCD,LMP,BPD/Weeks,BPD/Days,HC/Weeks,AC/Weeks,FL/Weeks,TCD/Weeks,LMP/Weeks,HC/Days,AC/Days,FL/Days,TCD/Days,LMP/Days
Unnamed: 0,,,,,,,,,,,,,,,,,,
1,20 2,21 1,22 0,20 5,20 4,20 4,20,2,21,22,20,20,20,1,0,5,4,4
2,25 3,24 1,27 2,26 1,26 2,26 2,25,3,24,27,26,26,26,1,2,1,2,2
3,19 1,20 2,21 1,20 5,20 4,20 4,19,1,20,21,20,20,20,2,1,5,4,4
4,24 2,26 1,27 1,25 6,26 1,26 0,24,2,26,27,25,26,26,1,1,6,1,0
5,18 2,19 1,19 6,20 1,19 1,19 3,18,2,19,19,20,19,19,1,6,1,1,3
6,21 1,22 1,22 0,21 5,21 5,22 0,21,1,22,22,21,21,22,1,0,5,5,0
7,27 1,28 2,28 3,26 4,27 1,27 0,27,1,28,28,26,27,27,2,3,4,1,0
8,23 4,22 1,23 6,23 0,22 5,23 0,23,4,22,23,23,22,23,1,6,0,5,0
9,24 3,25 1,25 6,24 6,24 0,24 0,24,3,25,25,24,24,24,1,6,6,0,0
10,22 4,22 6,21 5,20 5,21 6,21 6,22,4,22,21,20,21,21,6,5,5,6,6
11,19 2,18 3,21 0,20 4,19 3,19 3,19,2,18,21,20,19,19,3,0,4,3,3
12,27 1,26 4,28 0,28 1,26 1,26 0,27,1,26,28,28,26,26,4,0,1,1,0
13,23 1,22 5,22 5,23 4,23 0,23 0,23,1,22,22,23,23,23,5,5,4,0,0
14,20 4,20 5,20 3,21 2,21 2,20 0,20,4,20,20,21,21,20,5,3,2,2,0
15,25 2,25 5,25 1,25 4,25 0,25 0,25,2,25,25,25,25,25,5,1,4,0,0
16,23 2,23 0,23 1,24 2,24 2,24 2,23,2,23,23,24,24,24,0,1,2,2,2
17,25 4,24 1,23 5,26 3,26 4,26 0,25,4,24,23,26,26,26,1,5,3,4,0
18,22 4,22 0,21 3,22 0,22 0,22 0,22,4,22,21,22,22,22,0,3,0,0,0
19,21 5,22 0,22 2,22 0,22 1,22 0,21,5,22,22,22,22,22,0,2,0,1,0
20,24 2,25 0,20 5,21 0,24 6,20 5,24,2,25,20,21,24,20,0,5,0,6,5
21,20 0,19 5,22 5,23 1,22 0,20 0,20,0,19,22,23,22,20,5,5,1,0,0
22,21 0,21 3,21 1,21 4,21 5,21 1,21,0,21,21,21,21,21,3,1,4,5,1
23,20 6,21 0,24 5,23 0,23 0,24 0,20,6,21,24,23,23,24,0,5,0,0,0
24,23 5,23 2,20 1,21 2,20 4,23 0,23,5,23,20,21,20,23,2,1,2,4,0
25,20 3,19 5,23 2,23 5,23 4,24 0,20,3,19,23,23,23,24,5,2,5,4,0
26,21 1,22 0,22 6,23 0,22 5,23 0,21,1,22,22,23,22,23,0,6,0,5,0
27,26 6,28 0,25 2,26 4,26,26 5,26,6,28,25,26,26,26,0,2,4,,5
28,18 2,18 2,18 6,19 1,19 0,19 0,18,2,18,18,19,19,19,2,6,1,0,0
29,23 2,22 3,23 1,22 5,23 0,23 0,23,2,22,23,22,23,23,3,1,5,0,0
30,20 0,20 3,19 5,20 0,19 6,20 0,20,0,20,19,20,19,20,3,5,0,6,0
31,22 4,22 3,22 2,22 5,22 4,22 5,22,4,22,22,22,22,22,3,2,5,4,5
32,20 6,21 3,23 0,21 5,21 5,22 0,20,6,21,23,21,21,22,3,0,5,5,0
33,22 0,22 3,22 0,21 6,22 0,22 0,22,0,22,22,21,22,22,3,0,6,0,0
34,19 5,18 6,19 0,19 0,19 1,19 0,19,5,18,19,19,19,19,6,0,0,1,0
35,26 4,26 6,27 2,27 6,27 5,28 0,26,4,26,27,27,27,28,6,2,6,5,0
36,23,24 0,23 6,24,24 0,24 0,23,1,24,23,24,24,24,0,6,,0,0
37,24 2,24 3,26 0,25 3,25 2,26 0,24,1,24,26,25,25,26,3,0,3,2,0
38,19 4,20 0,19 6,19 6,19 5,20 0,19,4,20,19,19,19,20,0,6,6,5,0
39,22 5,22 5,23 0,22 3,22 3,22 3,22,5,22,23,22,22,22,5,0,3,3,3
40,26 0,26 3,25 3,25 5,25 4,26 0,26,0,26,25,25,25,26,3,3,5,4,0
41,25 4,25 3,27 6,27 0,27 2,27 0,25,4,25,27,27,27,27,3,6,0,2,0
42,23 3,23 3,24 0,23 5,23 5,23 0,23,3,23,24,23,23,23,3,0,5,5,0
43,20 2,20 6,22 0,21 5,21 3,21 0,20,2,20,22,21,21,21,6,0,5,3,0
44,19 6,20 0,19 5,19 6,20 0,20 0,19,6,20,19,19,20,20,0,5,6,0,0
45,25 45,25 5,26 5,26 0,26 2,26 0,25,45,25,26,26,26,26,5,5,0,2,0

In [52]:

main_1['HC/Weeks']=pd.to_numeric( main_1['HC/Weeks'])
main_1['AC/Weeks']=pd.to_numeric(main_1['AC/Weeks'])
main_1['FL/Weeks']=pd.to_numeric(main_1['FL/Weeks'])
main_1['TCD/Weeks']=pd.to_numeric(main_1['TCD/Weeks'])
main_1['LMP/Weeks']=pd.to_numeric(main_1['LMP/Weeks'])
main_1['HC/Days']=pd.to_numeric(main_1['HC/Days'])
main_1['AC/Days']=pd.to_numeric(main_1['AC/Days'])

main_1['LMP/Days']=pd.to_numeric(main_1['LMP/Days'])

In [53]:
main_1["FL/Days"].loc[36:36,]="0" 
main_1["TCD/Days"].loc[27:27,]="0"

C:\Users\jerrito\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [54]:
main_1["FL/Days"]=pd.to_numeric(main_1["FL/Days"])
main_1["TCD/Days"]=pd.to_numeric(main_1["TCD/Days"])

In [55]:
main_1

,BPD,HC,AC,FL,TCD,LMP,BPD/Weeks,BPD/Days,HC/Weeks,AC/Weeks,FL/Weeks,TCD/Weeks,LMP/Weeks,HC/Days,AC/Days,FL/Days,TCD/Days,LMP/Days
Unnamed: 0,,,,,,,,,,,,,,,,,,
1,20 2,21 1,22 0,20 5,20 4,20 4,20,2,21,22,20,20,20,1,0,5,4,4
2,25 3,24 1,27 2,26 1,26 2,26 2,25,3,24,27,26,26,26,1,2,1,2,2
3,19 1,20 2,21 1,20 5,20 4,20 4,19,1,20,21,20,20,20,2,1,5,4,4
4,24 2,26 1,27 1,25 6,26 1,26 0,24,2,26,27,25,26,26,1,1,6,1,0
5,18 2,19 1,19 6,20 1,19 1,19 3,18,2,19,19,20,19,19,1,6,1,1,3
6,21 1,22 1,22 0,21 5,21 5,22 0,21,1,22,22,21,21,22,1,0,5,5,0
7,27 1,28 2,28 3,26 4,27 1,27 0,27,1,28,28,26,27,27,2,3,4,1,0
8,23 4,22 1,23 6,23 0,22 5,23 0,23,4,22,23,23,22,23,1,6,0,5,0
9,24 3,25 1,25 6,24 6,24 0,24 0,24,3,25,25,24,24,24,1,6,6,0,0
10,22 4,22 6,21 5,20 5,21 6,21 6,22,4,22,21,20,21,21,6,5,5,6,6
11,19 2,18 3,21 0,20 4,19 3,19 3,19,2,18,21,20,19,19,3,0,4,3,3
12,27 1,26 4,28 0,28 1,26 1,26 0,27,1,26,28,28,26,26,4,0,1,1,0
13,23 1,22 5,22 5,23 4,23 0,23 0,23,1,22,22,23,23,23,5,5,4,0,0
14,20 4,20 5,20 3,21 2,21 2,20 0,20,4,20,20,21,21,20,5,3,2,2,0
15,25 2,25 5,25 1,25 4,25 0,25 0,25,2,25,25,25,25,25,5,1,4,0,0
16,23 2,23 0,23 1,24 2,24 2,24 2,23,2,23,23,24,24,24,0,1,2,2,2
17,25 4,24 1,23 5,26 3,26 4,26 0,25,4,24,23,26,26,26,1,5,3,4,0
18,22 4,22 0,21 3,22 0,22 0,22 0,22,4,22,21,22,22,22,0,3,0,0,0
19,21 5,22 0,22 2,22 0,22 1,22 0,21,5,22,22,22,22,22,0,2,0,1,0
20,24 2,25 0,20 5,21 0,24 6,20 5,24,2,25,20,21,24,20,0,5,0,6,5
21,20 0,19 5,22 5,23 1,22 0,20 0,20,0,19,22,23,22,20,5,5,1,0,0
22,21 0,21 3,21 1,21 4,21 5,21 1,21,0,21,21,21,21,21,3,1,4,5,1
23,20 6,21 0,24 5,23 0,23 0,24 0,20,6,21,24,23,23,24,0,5,0,0,0
24,23 5,23 2,20 1,21 2,20 4,23 0,23,5,23,20,21,20,23,2,1,2,4,0
25,20 3,19 5,23 2,23 5,23 4,24 0,20,3,19,23,23,23,24,5,2,5,4,0
26,21 1,22 0,22 6,23 0,22 5,23 0,21,1,22,22,23,22,23,0,6,0,5,0
27,26 6,28 0,25 2,26 4,26,26 5,26,6,28,25,26,26,26,0,2,4,0,5
28,18 2,18 2,18 6,19 1,19 0,19 0,18,2,18,18,19,19,19,2,6,1,0,0
29,23 2,22 3,23 1,22 5,23 0,23 0,23,2,22,23,22,23,23,3,1,5,0,0
30,20 0,20 3,19 5,20 0,19 6,20 0,20,0,20,19,20,19,20,3,5,0,6,0
31,22 4,22 3,22 2,22 5,22 4,22 5,22,4,22,22,22,22,22,3,2,5,4,5
32,20 6,21 3,23 0,21 5,21 5,22 0,20,6,21,23,21,21,22,3,0,5,5,0
33,22 0,22 3,22 0,21 6,22 0,22 0,22,0,22,22,21,22,22,3,0,6,0,0
34,19 5,18 6,19 0,19 0,19 1,19 0,19,5,18,19,19,19,19,6,0,0,1,0
35,26 4,26 6,27 2,27 6,27 5,28 0,26,4,26,27,27,27,28,6,2,6,5,0
36,23,24 0,23 6,24,24 0,24 0,23,1,24,23,24,24,24,0,6,0,0,0
37,24 2,24 3,26 0,25 3,25 2,26 0,24,1,24,26,25,25,26,3,0,3,2,0
38,19 4,20 0,19 6,19 6,19 5,20 0,19,4,20,19,19,19,20,0,6,6,5,0
39,22 5,22 5,23 0,22 3,22 3,22 3,22,5,22,23,22,22,22,5,0,3,3,3
40,26 0,26 3,25 3,25 5,25 4,26 0,26,0,26,25,25,25,26,3,3,5,4,0
41,25 4,25 3,27 6,27 0,27 2,27 0,25,4,25,27,27,27,27,3,6,0,2,0
42,23 3,23 3,24 0,23 5,23 5,23 0,23,3,23,24,23,23,23,3,0,5,5,0
43,20 2,20 6,22 0,21 5,21 3,21 0,20,2,20,22,21,21,21,6,0,5,3,0
44,19 6,20 0,19 5,19 6,20 0,20 0,19,6,20,19,19,20,20,0,5,6,0,0
45,25 45,25 5,26 5,26 0,26 2,26 0,25,45,25,26,26,26,26,5,5,0,2,0

In [56]:
file="New Second Trimester.xlsx"
main_1.to_excel(file)

In [57]:
file_main=main_1.loc[:,['BPD/Weeks','BPD/Days','HC/Weeks','AC/Weeks','FL/Weeks','TCD/Weeks','LMP/Weeks','HC/Days','AC/Days','FL/Days','TCD/Days','LMP/Days']]
file_main

,BPD/Weeks,BPD/Days,HC/Weeks,AC/Weeks,FL/Weeks,TCD/Weeks,LMP/Weeks,HC/Days,AC/Days,FL/Days,TCD/Days,LMP/Days
Unnamed: 0,,,,,,,,,,,,
1,20,2,21,22,20,20,20,1,0,5,4,4
2,25,3,24,27,26,26,26,1,2,1,2,2
3,19,1,20,21,20,20,20,2,1,5,4,4
4,24,2,26,27,25,26,26,1,1,6,1,0
5,18,2,19,19,20,19,19,1,6,1,1,3
6,21,1,22,22,21,21,22,1,0,5,5,0
7,27,1,28,28,26,27,27,2,3,4,1,0
8,23,4,22,23,23,22,23,1,6,0,5,0
9,24,3,25,25,24,24,24,1,6,6,0,0
10,22,4,22,21,20,21,21,6,5,5,6,6
11,19,2,18,21,20,19,19,3,0,4,3,3
12,27,1,26,28,28,26,26,4,0,1,1,0
13,23,1,22,22,23,23,23,5,5,4,0,0
14,20,4,20,20,21,21,20,5,3,2,2,0
15,25,2,25,25,25,25,25,5,1,4,0,0
16,23,2,23,23,24,24,24,0,1,2,2,2
17,25,4,24,23,26,26,26,1,5,3,4,0
18,22,4,22,21,22,22,22,0,3,0,0,0
19,21,5,22,22,22,22,22,0,2,0,1,0
20,24,2,25,20,21,24,20,0,5,0,6,5
21,20,0,19,22,23,22,20,5,5,1,0,0
22,21,0,21,21,21,21,21,3,1,4,5,1
23,20,6,21,24,23,23,24,0,5,0,0,0
24,23,5,23,20,21,20,23,2,1,2,4,0
25,20,3,19,23,23,23,24,5,2,5,4,0
26,21,1,22,22,23,22,23,0,6,0,5,0
27,26,6,28,25,26,26,26,0,2,4,0,5
28,18,2,18,18,19,19,19,2,6,1,0,0
29,23,2,22,23,22,23,23,3,1,5,0,0
30,20,0,20,19,20,19,20,3,5,0,6,0
31,22,4,22,22,22,22,22,3,2,5,4,5
32,20,6,21,23,21,21,22,3,0,5,5,0
33,22,0,22,22,21,22,22,3,0,6,0,0
34,19,5,18,19,19,19,19,6,0,0,1,0
35,26,4,26,27,27,27,28,6,2,6,5,0
36,23,1,24,23,24,24,24,0,6,0,0,0
37,24,1,24,26,25,25,26,3,0,3,2,0
38,19,4,20,19,19,19,20,0,6,6,5,0
39,22,5,22,23,22,22,22,5,0,3,3,3
40,26,0,26,25,25,25,26,3,3,5,4,0
41,25,4,25,27,27,27,27,3,6,0,2,0
42,23,3,23,24,23,23,23,3,0,5,5,0
43,20,2,20,22,21,21,21,6,0,5,3,0
44,19,6,20,19,19,20,20,0,5,6,0,0
45,25,45,25,26,26,26,26,5,5,0,2,0

In [58]:
file_main["BPD/Weeks"]=file_main["BPD/Weeks"]*7
file_main["HC/Weeks"]=file_main["HC/Weeks"]*7
file_main["AC/Weeks"]=file_main["AC/Weeks"]*7
file_main["FL/Weeks"]=file_main["FL/Weeks"]*7
file_main["TCD/Weeks"]=file_main["TCD/Weeks"]*7
file_main["LMP/Weeks"]=file_main["LMP/Weeks"]*7

In [59]:
file_main

,BPD/Weeks,BPD/Days,HC/Weeks,AC/Weeks,FL/Weeks,TCD/Weeks,LMP/Weeks,HC/Days,AC/Days,FL/Days,TCD/Days,LMP/Days
Unnamed: 0,,,,,,,,,,,,
1,140,2,147,154,140,140,140,1,0,5,4,4
2,175,3,168,189,182,182,182,1,2,1,2,2
3,133,1,140,147,140,140,140,2,1,5,4,4
4,168,2,182,189,175,182,182,1,1,6,1,0
5,126,2,133,133,140,133,133,1,6,1,1,3
6,147,1,154,154,147,147,154,1,0,5,5,0
7,189,1,196,196,182,189,189,2,3,4,1,0
8,161,4,154,161,161,154,161,1,6,0,5,0
9,168,3,175,175,168,168,168,1,6,6,0,0
10,154,4,154,147,140,147,147,6,5,5,6,6
11,133,2,126,147,140,133,133,3,0,4,3,3
12,189,1,182,196,196,182,182,4,0,1,1,0
13,161,1,154,154,161,161,161,5,5,4,0,0
14,140,4,140,140,147,147,140,5,3,2,2,0
15,175,2,175,175,175,175,175,5,1,4,0,0
16,161,2,161,161,168,168,168,0,1,2,2,2
17,175,4,168,161,182,182,182,1,5,3,4,0
18,154,4,154,147,154,154,154,0,3,0,0,0
19,147,5,154,154,154,154,154,0,2,0,1,0
20,168,2,175,140,147,168,140,0,5,0,6,5
21,140,0,133,154,161,154,140,5,5,1,0,0
22,147,0,147,147,147,147,147,3,1,4,5,1
23,140,6,147,168,161,161,168,0,5,0,0,0
24,161,5,161,140,147,140,161,2,1,2,4,0
25,140,3,133,161,161,161,168,5,2,5,4,0
26,147,1,154,154,161,154,161,0,6,0,5,0
27,182,6,196,175,182,182,182,0,2,4,0,5
28,126,2,126,126,133,133,133,2,6,1,0,0
29,161,2,154,161,154,161,161,3,1,5,0,0
30,140,0,140,133,140,133,140,3,5,0,6,0
31,154,4,154,154,154,154,154,3,2,5,4,5
32,140,6,147,161,147,147,154,3,0,5,5,0
33,154,0,154,154,147,154,154,3,0,6,0,0
34,133,5,126,133,133,133,133,6,0,0,1,0
35,182,4,182,189,189,189,196,6,2,6,5,0
36,161,1,168,161,168,168,168,0,6,0,0,0
37,168,1,168,182,175,175,182,3,0,3,2,0
38,133,4,140,133,133,133,140,0,6,6,5,0
39,154,5,154,161,154,154,154,5,0,3,3,3
40,182,0,182,175,175,175,182,3,3,5,4,0
41,175,4,175,189,189,189,189,3,6,0,2,0
42,161,3,161,168,161,161,161,3,0,5,5,0
43,140,2,140,154,147,147,147,6,0,5,3,0
44,133,6,140,133,133,140,140,0,5,6,0,0
45,175,45,175,182,182,182,182,5,5,0,2,0

In [60]:
file_main["BPD/W/d"]=file_main["BPD/Weeks"]+file_main["BPD/Days"]
file_main["HC/W/d"]=file_main["HC/Weeks"]+file_main["HC/Days"]
file_main["AC/W/d"]=file_main["AC/Weeks"]+file_main["AC/Days"]
file_main["FL/W/d"]=file_main["FL/Weeks"]+file_main["FL/Days"]
file_main["TCD/W/d"]=file_main["TCD/Weeks"]+file_main["TCD/Days"]
file_main["LMP/W/d"]=file_main["LMP/Weeks"]+file_main["LMP/Days"]
file_main

,BPD/Weeks,BPD/Days,HC/Weeks,AC/Weeks,FL/Weeks,TCD/Weeks,LMP/Weeks,HC/Days,AC/Days,FL/Days,TCD/Days,LMP/Days,BPD/W/d,HC/W/d,AC/W/d,FL/W/d,TCD/W/d,LMP/W/d
Unnamed: 0,,,,,,,,,,,,,,,,,,
1,140,2,147,154,140,140,140,1,0,5,4,4,142,148,154,145,144,144
2,175,3,168,189,182,182,182,1,2,1,2,2,178,169,191,183,184,184
3,133,1,140,147,140,140,140,2,1,5,4,4,134,142,148,145,144,144
4,168,2,182,189,175,182,182,1,1,6,1,0,170,183,190,181,183,182
5,126,2,133,133,140,133,133,1,6,1,1,3,128,134,139,141,134,136
6,147,1,154,154,147,147,154,1,0,5,5,0,148,155,154,152,152,154
7,189,1,196,196,182,189,189,2,3,4,1,0,190,198,199,186,190,189
8,161,4,154,161,161,154,161,1,6,0,5,0,165,155,167,161,159,161
9,168,3,175,175,168,168,168,1,6,6,0,0,171,176,181,174,168,168
10,154,4,154,147,140,147,147,6,5,5,6,6,158,160,152,145,153,153
11,133,2,126,147,140,133,133,3,0,4,3,3,135,129,147,144,136,136
12,189,1,182,196,196,182,182,4,0,1,1,0,190,186,196,197,183,182
13,161,1,154,154,161,161,161,5,5,4,0,0,162,159,159,165,161,161
14,140,4,140,140,147,147,140,5,3,2,2,0,144,145,143,149,149,140
15,175,2,175,175,175,175,175,5,1,4,0,0,177,180,176,179,175,175
16,161,2,161,161,168,168,168,0,1,2,2,2,163,161,162,170,170,170
17,175,4,168,161,182,182,182,1,5,3,4,0,179,169,166,185,186,182
18,154,4,154,147,154,154,154,0,3,0,0,0,158,154,150,154,154,154
19,147,5,154,154,154,154,154,0,2,0,1,0,152,154,156,154,155,154
20,168,2,175,140,147,168,140,0,5,0,6,5,170,175,145,147,174,145
21,140,0,133,154,161,154,140,5,5,1,0,0,140,138,159,162,154,140
22,147,0,147,147,147,147,147,3,1,4,5,1,147,150,148,151,152,148
23,140,6,147,168,161,161,168,0,5,0,0,0,146,147,173,161,161,168
24,161,5,161,140,147,140,161,2,1,2,4,0,166,163,141,149,144,161
25,140,3,133,161,161,161,168,5,2,5,4,0,143,138,163,166,165,168
26,147,1,154,154,161,154,161,0,6,0,5,0,148,154,160,161,159,161
27,182,6,196,175,182,182,182,0,2,4,0,5,188,196,177,186,182,187
28,126,2,126,126,133,133,133,2,6,1,0,0,128,128,132,134,133,133
29,161,2,154,161,154,161,161,3,1,5,0,0,163,157,162,159,161,161
30,140,0,140,133,140,133,140,3,5,0,6,0,140,143,138,140,139,140
31,154,4,154,154,154,154,154,3,2,5,4,5,158,157,156,159,158,159
32,140,6,147,161,147,147,154,3,0,5,5,0,146,150,161,152,152,154
33,154,0,154,154,147,154,154,3,0,6,0,0,154,157,154,153,154,154
34,133,5,126,133,133,133,133,6,0,0,1,0,138,132,133,133,134,133
35,182,4,182,189,189,189,196,6,2,6,5,0,186,188,191,195,194,196
36,161,1,168,161,168,168,168,0,6,0,0,0,162,168,167,168,168,168
37,168,1,168,182,175,175,182,3,0,3,2,0,169,171,182,178,177,182
38,133,4,140,133,133,133,140,0,6,6,5,0,137,140,139,139,138,140
39,154,5,154,161,154,154,154,5,0,3,3,3,159,159,161,157,157,157
40,182,0,182,175,175,175,182,3,3,5,4,0,182,185,178,180,179,182
41,175,4,175,189,189,189,189,3,6,0,2,0,179,178,195,189,191,189
42,161,3,161,168,161,161,161,3,0,5,5,0,164,164,168,166,166,161
43,140,2,140,154,147,147,147,6,0,5,3,0,142,146,154,152,150,147
44,133,6,140,133,133,140,140,0,5,6,0,0,139,140,138,139,140,140
45,175,45,175,182,182,182,182,5,5,0,2,0,220,180,187,182,184,182

In [61]:
file_main_1=file_main.loc[:,['BPD/W/d', 'HC/W/d', 'AC/W/d', 'FL/W/d', 'TCD/W/d', 'LMP/W/d']]
file_main_1

            BPD/W/d  HC/W/d  AC/W/d  FL/W/d  TCD/W/d  LMP/W/d
Unnamed: 0
1               142     148     154     145      144      144
2               178     169     191     183      184      184
3               134     142     148     145      144      144
4               170     183     190     181      183      182
5               128     134     139     141      134      136
6               148     155     154     152      152      154
7               190     198     199     186      190      189
8               165     155     167     161      159      161
9               171     176     181     174      168      168
10              158     160     152     145      153      153
11              135     129     147     144      136      136
12              190     186     196     197      183      182
13              162     159     159     165      161      161
14              144     145     143     149      149      140
15              177     180     176     179      175      175
16              163     161     162     170      170      170
17              179     169     166     185      186      182
18              158     154     150     154      154      154
19              152     154     156     154      155      154
20              170     175     145     147      174      145
21              140     138     159     162      154      140
22              147     150     148     151      152      148
23              146     147     173     161      161      168
24              166     163     141     149      144      161
25              143     138     163     166      165      168
26              148     154     160     161      159      161
27              188     196     177     186      182      187
28              128     128     132     134      133      133
29              163     157     162     159      161      161
30              140     143     138     140      139      140
31              158     157     156     159      158      159
32              146     150     161     152      152      154
33              154     157     154     153      154      154
34              138     132     133     133      134      133
35              186     188     191     195      194      196
36              162     168     167     168      168      168
37              169     171     182     178      177      182
38              137     140     139     139      138      140
39              159     159     161     157      157      157
40              182     185     178     180      179      182
41              179     178     195     189      191      189
42              164     164     168     166      166      161
43              142     146     154     152      150      147
44              139     140     138     139      140      140
45              220     180     187     182      184      182

In [33]:
q=pd.read_excel("C:/Users/jerrito/Desktop/Book1-1.xlsx")
qq=q.loc[1:45,]
qq.columns=['BPD/W/d','HC/W/d','AC/W/d','FL/W/d','TCD/W/d','LMP/W/d','AUA/w/d']


qq.set_index(["AUA/w/d"],inplace=True)
qq.index.array

<PandasArray>
[21.0, 25.5, 20.2, 25.5, 18.6, 21.5, 27.4, 23.1, 25.0, 22.0, 19.5, 27.3, 23.0,
 20.5, 25.3, 23.3, 25.0, 22.0, 22.0, 22.5, 21.2, 21.2, 22.2, 22.0, 21.5, 22.1,
 26.4, 18.4, 22.6, 20.0, 22.3, 21.5, 22.0, 19.1, 27.1, 23.6, 25.0, 19.5, 22.5,
 25.6, 26.3, 23.4, 21.2, 19.6, 26.0]
Length: 45, dtype: float64

In [74]:
q

,Second trimester,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,BPD W/D,HC w/d,AC w/d,FL w/d,TCD w/d,LMP w/d,AUA w/d
1,20.2,21.1,22,20.5,20.4,20.4,21
2,25.3,24.1,27.2,26.1,26.2,26.2,25.5
3,19.1,20.2,21.1,20.5,20.4,20.4,20.2
4,24.2,26.1,27.1,25.6,26.1,26,25.5
...,...,...,...,...,...,...,...
107,30.2,29.4,30.5,30,30.2,30,30.1
108,30.5,31,32,31.3,31.5,31.5,31.2
109,34.4,34.5,35.3,34.6,35,35,34.6
110,33.2,34,33,33.5,32.2,33,33.3
111,30.2,29.4,30.5,30,30.2,30,30.1

In [81]:
mat= pd.DataFrame({"AUA/w":[21, 25, 20, 25, 18, 21, 27, 23, 25, 22, 19, 27, 23,
 20, 25, 23, 25, 22, 22, 22, 21, 21, 22, 22, 21, 22,
 26, 18, 22, 20, 22, 21, 22, 19, 27, 23, 25, 19, 22,
 25, 26, 23, 21, 19, 26],"AUA/d":[0,5,2,5,6,5,4,1,0,0,5,3,0,5,3,3
 ,0,0,0,5,2,2,2,0,5,1,4,4,6,0,3,5,0,1,1,6,0,5,5,6,3,4,2,6,0]}
 )
mat.dtypes

AUA/w    int64
AUA/d    int64
dtype: object

In [82]:

mat["AUA/w"]=mat["AUA/w"]*7

mat["AVA/w/d"]=mat["AUA/w"]+mat["AUA/d"]
mat

    AUA/w  AUA/d  AVA/w/d
0     147      0      147
1     175      5      180
2     140      2      142
3     175      5      180
4     126      6      132
5     147      5      152
6     189      4      193
7     161      1      162
8     175      0      175
9     154      0      154
10    133      5      138
11    189      3      192
12    161      0      161
13    140      5      145
14    175      3      178
15    161      3      164
16    175      0      175
17    154      0      154
18    154      0      154
19    154      5      159
20    147      2      149
21    147      2      149
22    154      2      156
23    154      0      154
24    147      5      152
25    154      1      155
26    182      4      186
27    126      4      130
28    154      6      160
29    140      0      140
30    154      3      157
31    147      5      152
32    154      0      154
33    133      1      134
34    189      1      190
35    161      6      167
36    175      0      175
37    133      5      138
38    154      5      159
39    175      6      181
40    182      3      185
41    161      4      165
42    147      2      149
43    133      6      139
44    182      0      182

In [77]:
np.arange(0,45)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [89]:
a= [0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]
file_main_1.reset_index(drop=True,inplace=True)
file_main_1.drop(["AVA/w/d"], axis=1,inplace=True)
file_main_1

    BPD/W/d  HC/W/d  AC/W/d  FL/W/d  TCD/W/d  LMP/W/d
0       142     148     154     145      144      144
1       178     169     191     183      184      184
2       134     142     148     145      144      144
3       170     183     190     181      183      182
4       128     134     139     141      134      136
5       148     155     154     152      152      154
6       190     198     199     186      190      189
7       165     155     167     161      159      161
8       171     176     181     174      168      168
9       158     160     152     145      153      153
10      135     129     147     144      136      136
11      190     186     196     197      183      182
12      162     159     159     165      161      161
13      144     145     143     149      149      140
14      177     180     176     179      175      175
15      163     161     162     170      170      170
16      179     169     166     185      186      182
17      158     154     150     154      154      154
18      152     154     156     154      155      154
19      170     175     145     147      174      145
20      140     138     159     162      154      140
21      147     150     148     151      152      148
22      146     147     173     161      161      168
23      166     163     141     149      144      161
24      143     138     163     166      165      168
25      148     154     160     161      159      161
26      188     196     177     186      182      187
27      128     128     132     134      133      133
28      163     157     162     159      161      161
29      140     143     138     140      139      140
30      158     157     156     159      158      159
31      146     150     161     152      152      154
32      154     157     154     153      154      154
33      138     132     133     133      134      133
34      186     188     191     195      194      196
35      162     168     167     168      168      168
36      169     171     182     178      177      182
37      137     140     139     139      138      140
38      159     159     161     157      157      157
39      182     185     178     180      179      182
40      179     178     195     189      191      189
41      164     164     168     166      166      161
42      142     146     154     152      150      147
43      139     140     138     139      140      140
44      220     180     187     182      184      182

In [90]:

file_main_1["AVA/w/d"]=mat["AVA/w/d"]
file_main_1

    BPD/W/d  HC/W/d  AC/W/d  FL/W/d  TCD/W/d  LMP/W/d  AVA/w/d
0       142     148     154     145      144      144      147
1       178     169     191     183      184      184      180
2       134     142     148     145      144      144      142
3       170     183     190     181      183      182      180
4       128     134     139     141      134      136      132
5       148     155     154     152      152      154      152
6       190     198     199     186      190      189      193
7       165     155     167     161      159      161      162
8       171     176     181     174      168      168      175
9       158     160     152     145      153      153      154
10      135     129     147     144      136      136      138
11      190     186     196     197      183      182      192
12      162     159     159     165      161      161      161
13      144     145     143     149      149      140      145
14      177     180     176     179      175      175      178
15      163     161     162     170      170      170      164
16      179     169     166     185      186      182      175
17      158     154     150     154      154      154      154
18      152     154     156     154      155      154      154
19      170     175     145     147      174      145      159
20      140     138     159     162      154      140      149
21      147     150     148     151      152      148      149
22      146     147     173     161      161      168      156
23      166     163     141     149      144      161      154
24      143     138     163     166      165      168      152
25      148     154     160     161      159      161      155
26      188     196     177     186      182      187      186
27      128     128     132     134      133      133      130
28      163     157     162     159      161      161      160
29      140     143     138     140      139      140      140
30      158     157     156     159      158      159      157
31      146     150     161     152      152      154      152
32      154     157     154     153      154      154      154
33      138     132     133     133      134      133      134
34      186     188     191     195      194      196      190
35      162     168     167     168      168      168      167
36      169     171     182     178      177      182      175
37      137     140     139     139      138      140      138
38      159     159     161     157      157      157      159
39      182     185     178     180      179      182      181
40      179     178     195     189      191      189      185
41      164     164     168     166      166      161      165
42      142     146     154     152      150      147      149
43      139     140     138     139      140      140      139
44      220     180     187     182      184      182      182

In [76]:
data="Second Trim Calc1.xlsx"
file_main_1.to_excel(data)
file_main_1

            BPD/W/d  HC/W/d  AC/W/d  FL/W/d  TCD/W/d  LMP/W/d
Unnamed: 0
1               142     148     154     145      144      144
2               178     169     191     183      184      184
3               134     142     148     145      144      144
4               170     183     190     181      183      182
5               128     134     139     141      134      136
6               148     155     154     152      152      154
7               190     198     199     186      190      189
8               165     155     167     161      159      161
9               171     176     181     174      168      168
10              158     160     152     145      153      153
11              135     129     147     144      136      136
12              190     186     196     197      183      182
13              162     159     159     165      161      161
14              144     145     143     149      149      140
15              177     180     176     179      175      175
16              163     161     162     170      170      170
17              179     169     166     185      186      182
18              158     154     150     154      154      154
19              152     154     156     154      155      154
20              170     175     145     147      174      145
21              140     138     159     162      154      140
22              147     150     148     151      152      148
23              146     147     173     161      161      168
24              166     163     141     149      144      161
25              143     138     163     166      165      168
26              148     154     160     161      159      161
27              188     196     177     186      182      187
28              128     128     132     134      133      133
29              163     157     162     159      161      161
30              140     143     138     140      139      140
31              158     157     156     159      158      159
32              146     150     161     152      152      154
33              154     157     154     153      154      154
34              138     132     133     133      134      133
35              186     188     191     195      194      196
36              162     168     167     168      168      168
37              169     171     182     178      177      182
38              137     140     139     139      138      140
39              159     159     161     157      157      157
40              182     185     178     180      179      182
41              179     178     195     189      191      189
42              164     164     168     166      166      161
43              142     146     154     152      150      147
44              139     140     138     139      140      140
45              220     180     187     182      184      182

In [24]:

file_main_1.describe(include="all")

          BPD/W/d      HC/W/d      AC/W/d      FL/W/d     TCD/W/d     LMP/W/d
count   45.000000   45.000000   45.000000   45.000000   45.000000   45.000000
mean   159.066667  159.133333  162.044444  161.511111  161.022222  160.555556
std     19.599861   17.993181   18.229541   17.259546   17.230376   17.619147
min    128.000000  128.000000  132.000000  133.000000  133.000000  133.000000
25%    143.000000  146.000000  148.000000  149.000000  150.000000  145.000000
50%    158.000000  157.000000  160.000000  159.000000  159.000000  161.000000
75%    170.000000  171.000000  176.000000  178.000000  175.000000  175.000000
max    220.000000  198.000000  199.000000  197.000000  194.000000  196.000000

In [98]:
v=[46,47,48,49,50]
w=np.random.randint(130,200,size=(5,6))
ww=pd.DataFrame( data=w,index=v,columns=['BPD/W/d', 'HC/W/d', 'AC/W/d', 'FL/W/d', 'TCD/W/d', 'LMP/W/d'])

ww['AVA/w/d']=(ww['BPD/W/d']+ww['HC/W/d']+ww['AC/W/d']+ww['FL/W/d']+ww['TCD/W/d']+ww[ 'LMP/W/d'])/6
ww['AVA/w/d']=ww['AVA/w/d'].apply(np.int64)

ww

    BPD/W/d  HC/W/d  AC/W/d  FL/W/d  TCD/W/d  LMP/W/d  AVA/w/d
46      142     135     188     175      155      132      154
47      174     151     195     176      138      184      169
48      133     180     130     165      150      188      157
49      158     174     182     186      179      149      171
50      161     147     161     188      162      163      163

In [99]:
alls=[file_main_1,ww]
final_results=pd.concat(alls)
final_results

    BPD/W/d  HC/W/d  AC/W/d  FL/W/d  TCD/W/d  LMP/W/d  AVA/w/d
0       142     148     154     145      144      144      147
1       178     169     191     183      184      184      180
2       134     142     148     145      144      144      142
3       170     183     190     181      183      182      180
4       128     134     139     141      134      136      132
5       148     155     154     152      152      154      152
6       190     198     199     186      190      189      193
7       165     155     167     161      159      161      162
8       171     176     181     174      168      168      175
9       158     160     152     145      153      153      154
10      135     129     147     144      136      136      138
11      190     186     196     197      183      182      192
12      162     159     159     165      161      161      161
13      144     145     143     149      149      140      145
14      177     180     176     179      175      175      178
15      163     161     162     170      170      170      164
16      179     169     166     185      186      182      175
17      158     154     150     154      154      154      154
18      152     154     156     154      155      154      154
19      170     175     145     147      174      145      159
20      140     138     159     162      154      140      149
21      147     150     148     151      152      148      149
22      146     147     173     161      161      168      156
23      166     163     141     149      144      161      154
24      143     138     163     166      165      168      152
25      148     154     160     161      159      161      155
26      188     196     177     186      182      187      186
27      128     128     132     134      133      133      130
28      163     157     162     159      161      161      160
29      140     143     138     140      139      140      140
30      158     157     156     159      158      159      157
31      146     150     161     152      152      154      152
32      154     157     154     153      154      154      154
33      138     132     133     133      134      133      134
34      186     188     191     195      194      196      190
35      162     168     167     168      168      168      167
36      169     171     182     178      177      182      175
37      137     140     139     139      138      140      138
38      159     159     161     157      157      157      159
39      182     185     178     180      179      182      181
40      179     178     195     189      191      189      185
41      164     164     168     166      166      161      165
42      142     146     154     152      150      147      149
43      139     140     138     139      140      140      139
44      220     180     187     182      184      182      182
46      142     135     188     175      155      132      154
47      174     151     195     176      138      184      169
48      133     180     130     165      150      188      157
49      158     174     182     186      179      149      171
50      161     147     161     188      162      163      163

In [100]:
cal=final_results.describe(include="all")
cal/7

,BPD/W/d,HC/W/d,AC/W/d,FL/W/d,TCD/W/d,LMP/W/d,AVA/w/d
count,7.142857,7.142857,7.142857,7.142857,7.142857,7.142857,7.142857
mean,22.645714,22.708571,23.280000,23.308571,22.942857,22.974286,22.882857
std,2.744612,2.556803,2.720181,2.472398,2.420412,2.574454,2.332375
min,18.285714,18.285714,18.571429,19.000000,19.000000,18.857143,18.571429
25%,20.321429,20.892857,21.214286,21.357143,21.428571,20.785714,21.392857
50%,22.571429,22.428571,23.000000,23.000000,22.642857,23.000000,22.428571
75%,24.285714,24.750000,25.392857,25.535714,24.964286,25.750000,24.857143
max,31.428571,28.285714,28.428571,28.142857,27.714286,28.000000,27.571429

In [35]:

pearson, _=pearsonr(file_main_1["BPD/W/d"],file_main_1["HC/W/d"])
pearson

0.9139917012765559

In [101]:
final_results.corr(method="pearson")

          BPD/W/d    HC/W/d    AC/W/d    FL/W/d   TCD/W/d   LMP/W/d   AVA/w/d
BPD/W/d  1.000000  0.824094  0.751391  0.768681  0.820774  0.778341  0.903734
HC/W/d   0.824094  1.000000  0.631355  0.741369  0.844371  0.825513  0.906076
AC/W/d   0.751391  0.631355  1.000000  0.876620  0.782397  0.707180  0.871547
FL/W/d   0.768681  0.741369  0.876620  1.000000  0.867908  0.821096  0.925322
TCD/W/d  0.820774  0.844371  0.782397  0.867908  1.000000  0.780646  0.922698
LMP/W/d  0.778341  0.825513  0.707180  0.821096  0.780646  1.000000  0.887258
AVA/w/d  0.903734  0.906076  0.871547  0.925322  0.922698  0.887258  1.000000

In [104]:

dd="Final_result.xlsx"
final_results.to_excel(dd)